data_location: /pio/lscratch/1/i247948/lastfm_train/**/**/**/*.json
min_elems: 100
uniq_map_file: /pio/lscratch/1/i247948/pickle_train/uniq.p
runiq_map_file: /pio/lscratch/1/i247948/pickle_train/runiq.p
pickle_dir: /pio/lscratch/1/i247948/pickle_train/
